Repository jenkins-x-apps/jx-app-anchore, pull requests merged in 2020-05, with the labels that each got.

#3 Getting added to ownersfile so I can update
  OWNERS
Labels: size/XS

#4 chore: adding sharepointoscar to approvers and reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#6 chore: upgrading anchore version
  README.md
  jx-app-anchore/README.md
  jx-app-anchore/requirements.yaml
Labels: approved, lgtm, size/M
